server.port=8080
spring.application.name=myapp
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
# Actuators
management.endpoint.mappings.enabled=true
spring.jmx.enabled=true
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# JWT 15 min
authentication.jwt.expiration.time=900000
# I can also change the path for swagger
# https://howtodoinjava.com/spring-boot/springdoc-openapi-rest-documentation/
springdoc.swagger-ui.path=/bilguun.html
# MongoDB Configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=mydb
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bilguun.ing@gmail.com
spring.mail.password=vjqiratprffifsoa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# End points
api.path=https://jsonplaceholder.typicode.com/todos
server.tomcat.relaxed-query-chars=|,{,},[,]
