server.port=8080
spring.application.name=myapp
spring.datasource.url=jdbc:mysql://localhost:3306/EasyAdmin?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Enkhzaya1!
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
# Actuators
management.endpoint.mappings.enabled=true
spring.jmx.enabled=true
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# JWT 5 min
authentication.jwt.expiration.time=300000
# I can also change the path for swagger
# https://howtodoinjava.com/spring-boot/springdoc-openapi-rest-documentation/
springdoc.swagger-ui.path=/bilguun.html
# MongoDB Configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=mydb
# End points
api.path=https://jsonplaceholder.typicode.com/todos
